# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_item_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
